#!/usr/bin/env node
/**
 * Prepend latest delta summary to Lexery - Log.md after the title heading.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SYSTEM_DIR = join(__dirname, '..');
const VAULT_DIR = dirname(SYSTEM_DIR);
const LOGS_DIR = join(SYSTEM_DIR, 'logs');
const LOG_FILE = join(VAULT_DIR, 'Lexery - Log.md');

function todayCompact() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}${m}${day}`;
}

function todayHeadingDate() {
  return new Date().toISOString().slice(0, 10);
}

function latestDeltaPath() {
  const compact = todayCompact();
  const todayFile = join(LOGS_DIR, `delta-summary-${compact}.md`);
  if (existsSync(todayFile)) return todayFile;

  let best = '';
  let bestMtime = 0;
  try {
    for (const name of readdirSync(LOGS_DIR)) {
      if (!name.startsWith('delta-summary-') || !name.endsWith('.md')) continue;
      const full = join(LOGS_DIR, name);
      const st = statSync(full);
      if (st.mtimeMs > bestMtime) {
        bestMtime = st.mtimeMs;
        best = full;
      }
    }
  } catch {
    return '';
  }
  return best;
}

const deltaFile = latestDeltaPath();

if (!deltaFile || !existsSync(deltaFile)) {
  console.error('No delta summary found. Run generate-delta.mjs first.');
  process.exit(0);
}

const raw = readFileSync(deltaFile, 'utf8');
const lines = raw.split(/\r?\n/);
let start = 0;
if (lines[0]?.startsWith('# ')) {
  start = 1;
  while (start < lines.length && lines[start].trim() === '') start++;
}
const deltaContent = lines.slice(start).join('\n').trimEnd();

const dateStr = todayHeadingDate();
const newEntry = `
## ${dateStr} — Automated Sync

${deltaContent}

> Auto-generated by [[Lexery - Automation Architecture|maintenance automation]]. See [[Lexery - Brain Architecture]] for system shape.

---
`;

if (!existsSync(LOG_FILE)) {
  writeFileSync(LOG_FILE, `# Lexery - Log\n${newEntry}\n`);
  console.log(`Created ${LOG_FILE} with first entry.`);
  process.exit(0);
}

const logText = readFileSync(LOG_FILE, 'utf8');
const out = logText.replace(
  /^# Lexery - Log\s*$/m,
  `# Lexery - Log\n${newEntry.trimEnd()}\n`,
);

if (out === logText) {
  console.error('Could not find "# Lexery - Log" heading; file unchanged.');
  process.exit(1);
}

writeFileSync(LOG_FILE, out);
console.log(`Log updated: ${LOG_FILE}`);
